extends StaticBody3D

enum BlockType { STRAIGHT, START, FINISH, BOOSTER, RAMP, CURVE_TIGHT, CURVE_WIDE, STRAIGHT_LONG, CURVE_EXTRA_WIDE, SIDE_PIPE_LEFT, SIDE_PIPE_RIGHT, STRAIGHT_LONG_WO_WALLS }

@export var type: BlockType = BlockType.STRAIGHT
